### PR TITLE
Clarify error message

### LINKED ISSUE #23112: Change to a more clear message
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target

### What specific section or headline is this issue about?

try_it

### What information was incorrect, unhelpful, or incomplete?

I'm not a native English speaker. Unfortunately, I erroneously translated the message "Foo() must **be** called with new" in my head to just the opposite: "Foo() must **have been** called with the new operator". Hence I get confused about the behavior of the invocation. Please consider changing the message to a more clear version in active tense, e.g., "You must call Foo() with 'new'. Abort. ". 

### What did you expect to see?

just the opposite behavior

### Do you have any supporting links, references, or citations?

_No response_

### Do you have anything more you want to share?

_No response_

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/new.target`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/new.target/index.md
* Last commit: https://github.com/mdn/content/commit/0f248adcab759bdad247a5dbfb7da12dc32bce59
* Document last modified: 2022-12-13T20:26:24.000Z

</details>

### PR DESCRIPTION
**Pull request by dawei-wang**
Fix mdn/content#23112

### CODE REVIEW

**Review by NiedziolkaMichal — CHANGES_REQUESTED** [review]
Thanks for making this PR. Word `Map` should be `Foo` in both messages. Could you change it, please?

**Review by NiedziolkaMichal — APPROVED** [review]
Everything looks good now, thanks

File: live-examples/js-examples/expressions/expressions-newtarget.js [hunk 1]
```diff
@@ -1,10 +1,10 @@
 function Foo() {
-  if (!new.target) { throw 'Foo() must be called with new'; }
+  if (!new.target) { throw 'TypeError: calling Foo constructor without new is invalid'; }
```
Comment (Josh-Cena) [inline live-examples/js-examples/expressions/expressions-newtarget.js:2]: Oops, this should really be: `throw new TypeError ("calling Foo constructor without new is invalid")`

But when we one day enable ESLint, this would be caught by `no-throw-literals` anyway.

Comment (NiedziolkaMichal) [reply live-examples/js-examples/expressions/expressions-newtarget.js:2]: You are right. I see that string is thrown also in a few other examples, so I will change them all at once. Thanks
