### PR TITLE
[Fix]groups-and-backreferences-#2664

### LINKED ISSUE #2664: Live example on the groups and backreferences page has inconsistent name
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions/Groups_and_backreferences

### What specific section or headline is this issue about?

"Try it" section

### What information was incorrect, unhelpful, or incomplete?

The title of the article is "Groups and backreferences", but the name of the live example is "RegExp Groups and ranges".

Also, it would be better if the example can show the usage of backreferences.

### What did you expect to see?

- The name of the live example is something like "RegExp Groups and backreferences".
- Rewrite the example to show how to use backreferences.

### Do you have any supporting links, references, or citations?

_No response_

### Do you have anything more you want to share?

_No response_

### PR DESCRIPTION
**Pull request by Himanshuch8055**
### Description
The article's title "Groups and backreferences" doesn't match the name of the live example "RegExp Groups and ranges". Additionally, the example should showcase the usage of backreferences.
I have resolved the issue.

### Related issues and pull requests
Fixes #2664

### CODE REVIEW

File: live-examples/js-examples/regexp/regexp-groups-ranges.js [hunk 1]
```diff
@@ -1,10 +1,14 @@
...
 console.log(`Width: ${match[1]} / Height: ${match[2]}.`);
 // Expected output: "Width: 1440 / Height: 900."
+
+// Backreferences
+const quote = `Single quote "'" and double quote '"'`;
+const regexpQuotes = /(['"]).*?\1/g;
+for (const match of quote.matchAll(regexpQuotes)) {
+  console.log(match[0]);
+}
+// Expected output: '"'"' '"'"'
```
Comment (Josh-Cena) [inline live-examples/js-examples/regexp/regexp-groups-ranges.js]: Let's use an example that's not so confusing with so many nested quotes. What about the [duplicate words](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Backreference#matching_duplicate_words) example instead?

**Review by Josh-Cena — APPROVED** [review]
Looks good, thanks
